import { chromium } from "playwright";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
const BASE = process.env.URL || "http://127.0.0.1:5180/";
const out = fileURLToPath(new URL("./shots/", import.meta.url)); fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(() => { localStorage.setItem("dm2-reduce", "true"); localStorage.setItem("dm2-name", '"Alex"'); });
const p = await ctx.newPage(); const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); }); p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
await p.goto(BASE + "#/jugar/llaves/n3"); await p.waitForSelector(".choice"); await p.waitForTimeout(400);
await p.screenshot({ path: out + "v3-play.png" });
await p.click('.obj[data-o="llaves"]'); await p.waitForSelector(".peek"); await p.screenshot({ path: out + "v3-peek-obj.png" });
await p.keyboard.press("Escape");
await p.click(".tile >> nth=0"); await p.waitForSelector(".peek"); await p.screenshot({ path: out + "v3-peek-tile.png" });
await p.keyboard.press("Escape");
await p.goto(BASE + "#/jugar/llaves/n2b"); await p.waitForSelector(".fact"); await p.click('[data-src]'); await p.waitForSelector(".peek"); await p.screenshot({ path: out + "v3-peek-src.png" });
await p.goto(BASE + "#/jugar/sofi/n3"); await p.waitForSelector(".choice"); await p.waitForTimeout(300); await p.screenshot({ path: out + "v3-sofi.png" });
console.log("errores:", errs.length ? errs : "ninguno"); await b.close();
