import { chromium } from "playwright";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
const BASE = "http://127.0.0.1:5180/";
const out = fileURLToPath(new URL("./shots/", import.meta.url)); fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(() => { localStorage.setItem("dm2-reduce", "true"); localStorage.setItem("dm2-name", '"Alex"'); });
const p = await ctx.newPage(); const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); }); p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
await p.goto(BASE); await p.waitForTimeout(600); await p.screenshot({ path: out + "v4-home.png" });
await p.goto(BASE + "#/jugar/llaves"); await p.waitForSelector(".choice");
await p.click('.choice[data-k="1"]'); await p.waitForSelector(".fact"); await p.waitForSelector("#go"); await p.click("#go");
await p.waitForSelector(".choice"); await p.waitForTimeout(300);
console.log("objetos en mochila tras 2 etapas:", await p.$$eval("#inv .obj", (e) => e.map((x) => x.textContent.trim())));
await p.screenshot({ path: out + "v4-play.png" });
await p.click('#inv .obj >> nth=0'); await p.waitForSelector(".peek"); await p.screenshot({ path: out + "v4-peek.png" });
await p.keyboard.press("Escape");
await p.click('.choice[data-k="0"]'); await p.waitForSelector(".fact"); await p.waitForTimeout(300);
await p.screenshot({ path: out + "v4-fact.png", fullPage: false });
await p.evaluate(() => document.querySelector(".fact").scrollIntoView({ block: "center" })); await p.waitForTimeout(200); await p.screenshot({ path: out + "v4-fact2.png" });
await p.setViewportSize({ width: 390, height: 800 });
await p.goto(BASE + "#/casos"); await p.waitForTimeout(400); await p.screenshot({ path: out + "v4-m-casos.png" });
console.log("errores:", errs.length ? errs : "ninguno"); await b.close();
